{"version":3,"file":"retry.js","sourceRoot":"","sources":["../../../src/public/common/retry.ts"],"names":[],"mappings":"AAAA;;;;;;;;;;;;GAYG;AACH,MAAM,CAAC,KAAK,UAAU,mCAAmC,CACvD,aAA+B,EAC/B,iBAAyC;IAEzC,IAAI,SAAwB,CAAA;IAC5B,IAAI;QACF,SAAS,GAAG,MAAM,aAAa,EAAE,CAAA;QACjC,OAAO,SAAS,CAAA;QAChB,qDAAqD;KACtD;IAAC,OAAO,GAAG,EAAE;QACZ,6DAA6D;QAC7D,MAAM,iBAAiB,EAAE,CAAA;QACzB,OAAO,aAAa,EAAE,CAAA;KACvB;AACH,CAAC","sourcesContent":["/**\n * Perform an action optimistically. If it fails the first time, first initiate\n * a provided recovery procedure, then retry the action. If it fails again,\n * throw the error.\n *\n * This is useful for actions that may fail due to recoverable errors, such as\n * an expired token that can be refreshed. In this case, the recovery procedure\n * would refresh the token.\n *\n * @param performAction - The action to perform.\n * @param recoveryProcedure - The recovery procedure to perform if the action\n * fails the first time.\n */\nexport async function performActionWithRetryAfterRecovery<T>(\n  performAction: () => Promise<T>,\n  recoveryProcedure: () => Promise<unknown>,\n): Promise<T> {\n  let returnVal: T | undefined\n  try {\n    returnVal = await performAction()\n    return returnVal\n    // eslint-disable-next-line no-catch-all/no-catch-all\n  } catch (err) {\n    // Run the provided recovery procedure, then retry the action\n    await recoveryProcedure()\n    return performAction()\n  }\n}\n"]}